import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='eng'>
      
    <body>
        <div className='main'>
            <div className="gradient"/>
        </div>

            <main className='app relative z-20'>
                {children}
            </main>
    </body>
</html>
  )
}
